sudo: false
language: node_js
node_js:
  - 'iojs'
  - '0.12'
  - '0.10'
before_script:
  - npm install -g istanbul
  - npm install -g mocha
  - npm install -g codeclimate-test-reporter
after_success:
  - NODE_ENV=test LOG_LV=info istanbul cover _mocha -- -R spec test/test.js
  - codeclimate-test-reporter < ./coverage/lcov.info
